from typing import Protocol

from ..entities import CatalogCacheEntry


class CatalogCacheGateway(Protocol):
    async def get_epoch(self, connection_id: str, revision: str) -> int: ...
    async def increment_epoch(self, connection_id: str, revision: str) -> int: ...
    async def get(self, key: str) -> CatalogCacheEntry | None: ...
    async def set(self, key: str, entry: CatalogCacheEntry, ttl_seconds: int) -> None: ...
    async def try_acquire(self, key: str, ttl_seconds: int) -> str | None: ...
    async def release(self, key: str, token: str) -> None: ...
    async def wait_for_entry(self, key: str, timeout_seconds: float) -> CatalogCacheEntry | None: ...
