from __future__ import annotations

from collections.abc import Iterable
from typing import Protocol, TypeVar

from .keys import IndexKeyBase

T = TypeVar("T")
K = TypeVar("K", bound=IndexKeyBase)
V = TypeVar("V")


class BlobStore(Protocol):
    async def put(self, key: str, payload: bytes, ttl: int | None = None) -> None: ...
    async def get(self, key: str) -> bytes | None: ...
    async def compare_and_set(
        self,
        key: str,
        *,
        expected: bytes | None,
        payload: bytes,
        ttl: int | None = None,
    ) -> bool: ...
    async def get_many(self, keys: Iterable[str]) -> list[bytes | None]: ...
    async def has(self, key: str) -> bool: ...
    async def has_many(self, keys: Iterable[str]) -> bool: ...
    async def keys(self, prefix: str) -> list[str]: ...
    async def remove(self, key: str, *keys: str) -> None: ...
    async def clear(self) -> None: ...
    async def close(self) -> None: ...


class ObjectStore(Protocol[T]):
    async def put(self, key: str, obj: T, ttl_lifetime: int | None = None) -> None: ...
    async def get(self, key: str) -> T | None: ...
    async def get_many(self, keys: Iterable[str]) -> list[T | None]: ...
    async def has(self, key: str) -> bool: ...
    async def has_many(self, keys: Iterable[str]) -> bool: ...
    async def keys(self, prefix: str) -> list[str]: ...
    async def remove(self, key: str, *keys: str) -> None: ...
    async def clear(self) -> None: ...
    async def close(self) -> None: ...


class EncodedObjectStore(ObjectStore[T], Protocol[T]):
    """Object store that can detach serialization from async I/O."""

    def encode(self, obj: T) -> bytes: ...
    def decode(self, payload: bytes) -> T: ...
    async def put_encoded(self, key: str, payload: bytes, ttl_lifetime: int | None = None) -> None: ...
    async def get_encoded(self, key: str) -> bytes | None: ...
    async def compare_and_set_encoded(
        self,
        key: str,
        *,
        expected: bytes | None,
        payload: bytes,
        ttl_lifetime: int | None = None,
    ) -> bool: ...


class IndexStore(Protocol[K, V]):
    async def put(self, index_key: K, value: V, ttl: int | None = None) -> None: ...
    async def get(self, store_key: str) -> V | None: ...
    async def contains(self, index_key: K) -> bool: ...
    async def query(self, index_key: K) -> list[V]: ...
    async def keys(self, key_type: type[K]) -> list[K]: ...
    async def remove(self, index_key: K) -> None: ...
    async def clear(self) -> None: ...
    async def reindex(self, entries: Iterable[tuple[K, V]], *, clear_first: bool = True) -> int: ...
    async def close(self) -> None: ...
