from enum import Enum


class ExceptionCategory(Enum):
    DB = 'DATABASE'
    DATAFRAME = "DATAFRAME"
    SERVICE_GATEWAY_ADMIN = "GATEWAY_ADMIN"
    SERVICE_GATEWAY_EXCEPTION_REGISTRY = "GATEWAY_EXCEPTION_REGISTRY"
    SERVICE_GATEWAY_INTERNAL = "GATEWAY_INTERNAL"
    SERVICE_GATEWAY_PROJECT = "GATEWAY_PROJECT"
    SERVICE_GATEWAY_TASK = "GATEWAY_PROJECT"
    SERVICE_GATEWAY_PUBLIC = "GATEWAY_PUBLIC"
    SERVICE_GATEWAY_STORAGE = "GATEWAY_STORAGE"
    SERVICE_GATEWAY_UTILS = "GATEWAY_UTILS"
    SERVICE_GATEWAY_QUEUE = "GATEWAY_QUEUE"
    SERVICE_GATEWAY_WS = "GATEWAY_WS"
    SERVICE_GATEWAY_CACHE = "GATEWAY_CACHE"
    SERVICE_TASK_WORKER_CACHE = "TASK_WORKER_CACHE"
    SERVICE_TASK_WORKER_TASKS = "TASK_WORKER_TASKS"
    SERVICE_PROJECT_SCHEDULER_TASKS = "PROJECT_SCHEDULER_TASKS"
    WORKER_CLIENT = "WORKER_CLIENT"
    ORCHESTRATOR_CLIENT = "ORCHESTRATOR_CLIENT"
    SCHEDULER_CLIENT = "SCHEDULER_CLIENT"
    S3 = "S3"
    FTP = "FTP"
    HIGH = "high"
    CRITICAL = "critical"
    UNKNOWN = "UNKNOWN"

    # DB Entities
    USER = "USER"
    ORGANIZATION = "ORGANIZATION"
    PROJECT = "PROJECT"
    TASK = "TASK"
    QUEUE_TOPIC = "QUEUE_TOPIC"
    GRAPH = "GRAPH"
    GRAPH_NODE = "GRAPH_NODE"
    GRAPH_EDGE = "GRAPH_EDGE"
    SUBGRAPH = "SUBGRAPH"

    NODES = "NODES"

    # CRUD layer
    CRUD_USER = "CRUD_USER"
    CRUD_ORGANIZATION = "CRUD_ORGANIZATION"
    CRUD_PROJECT = "CRUD_PROJECT"
    CRUD_PROJECT_SCHEDULE = "CRUD_PROJECT_SCHEDULE"
    CRUD_DB_CONNECTION = "CRUD_DB_CONNECTION"
    CRUD_QUEUE_TOPIC = "CRUD_QUEUE_TOPIC"
    CRUD_TASK = "CRUD_TASK"
    CRUD_GRAPH = "CRUD_GRAPH"
    CRUD_GRAPH_NODE = "CRUD_GRAPH_NODE"
    CRUD_GRAPH_EDGE = "CRUD_GRAPH_EDGE"
    CRUD_SUBGRAPH = "CRUD_SUBGRAPH"


class ExceptionType(Enum):
    CUSTOM = 'CUSTOM'
    HTTP_GENERATED = 'HTTP_GENERATED'
