"""ADD initial tables

Revision ID: 0001
Revises: 
Create Date: 2025-08-07 14:22:03.721362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logs',
                    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('level', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('service_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('logger_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('module', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('function', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('line', sa.Integer(), nullable=True),
                    sa.Column('extra', sa.JSON(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_logs_created_at'), 'logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_logs_level'), 'logs', ['level'], unique=False)
    op.create_index(op.f('ix_logs_service_name'), 'logs', ['service_name'], unique=False)
    op.create_table('users',
                    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
                    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
                    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
                    sa.Column('password_version', sa.Integer(), nullable=True),
                    sa.Column('auth_provider', sa.String(length=16), nullable=False),
                    sa.Column('user_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
                    sa.Column('is_verified', sa.Boolean(), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=False),
                    sa.Column('signed_up_at', sa.TIMESTAMP(timezone=True), nullable=False),
                    sa.Column('last_password_change', sa.TIMESTAMP(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('db_connections',
                    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
                    sa.Column('type', sa.Enum('MYSQL', 'POSTGRES', 'CLICKHOUSE', 'MONGODB', 'MSSQL',
                                              name='databaseconnectiontype'), nullable=False),
                    sa.Column('host', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
                    sa.Column('port', sa.Integer(), nullable=False),
                    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
                    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
                    sa.Column('database', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
                    sa.Column('options', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('is_active', sa.Boolean(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('additional_properties', sa.types.JSON(), nullable=True),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'],
                                            name='db_connections_user_id_fkey'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('projects',
                    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'],
                                            name='projects_user_id_fkey'),
                    sa.UniqueConstraint('id', 'user_id', name='unique_project_id_user_id'),
                    sa.PrimaryKeyConstraint('id'),
                    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=False)
    op.create_table('graph_edges',
                    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('ui_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('source_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('target', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('target_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
                    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(['project_id', 'user_id'], ['projects.id', 'projects.user_id'],
                                            name='fk_graph_edges_project_user'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('ui_id', 'project_id', name='unique_ui_id_per_project_for_edges')
                    )
    op.create_index(op.f('ix_graph_edges_ui_id'), 'graph_edges', ['ui_id'], unique=False)
    op.create_table('graph_nodes',
                    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('ui_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('position_x', sa.Float(), nullable=False),
                    sa.Column('position_y', sa.Float(), nullable=False),
                    sa.Column('selected', sa.Boolean(), nullable=False),
                    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('input_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
                    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
                    sa.ForeignKeyConstraint(['project_id', 'user_id'], ['projects.id', 'projects.user_id'],
                                            name='fk_graph_nodes_project_user'),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('ui_id', 'project_id', name='unique_ui_id_per_project_for_nodes')
                    )
    op.create_index(op.f('ix_graph_nodes_ui_id'), 'graph_nodes', ['ui_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_graph_nodes_ui_id'), table_name='graph_nodes')
    op.drop_table('graph_nodes')
    op.drop_index(op.f('ix_graph_edges_ui_id'), table_name='graph_edges')
    op.drop_table('graph_edges')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    op.drop_table('db_connections')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_logs_service_name'), table_name='logs')
    op.drop_index(op.f('ix_logs_level'), table_name='logs')
    op.drop_index(op.f('ix_logs_created_at'), table_name='logs')
    op.drop_table('logs')
    # ### end Alembic commands ###
