"""UPD db_log model

Revision ID: 0003
Revises: 0002
Create Date: 2025-08-11 19:51:33.243966

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('logs', 'extra')

    op.add_column('logs', sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('logs', sa.Column('task_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))

    op.create_index(op.f('ix_logs_user_id'), 'logs', ['user_id'], unique=False)
    op.create_foreign_key(
        "logs_user_id_fkey",
        source_table="logs",
        referent_table="users",
        local_cols=["user_id"],
        remote_cols=["id"],
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("logs_user_id_fkey", 'logs', type_='foreignkey')

    op.drop_index(op.f('ix_logs_user_id'), table_name='logs')

    op.drop_column('logs', 'task_id')
    op.drop_column('logs', 'user_id')
    op.add_column(
        "logs",
        sa.Column("extra", postgresql.JSON(), nullable=True),
    )
