"""add task queue table

Revision ID: 0006
Revises: 0005
Create Date: 2025-10-07 18:23:42.743880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'task_queue',
        sa.Column('task_id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('project_id', sa.String(), nullable=False),
        sa.Column('mode', sa.Enum('FULL', 'METADATA_ONLY', name='task_queue_exec_mode', native_enum=False),
                  nullable=False),
        sa.Column('force_exec', sa.Boolean(), nullable=False),
        sa.Column('status',
                  sa.Enum('PENDING', 'STARTED', 'RUNNING', 'SUCCESS', 'ERROR', 'CANCELLED', name='task_queue_status',
                          native_enum=False), nullable=False),
        sa.Column('queued_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_task_queue_user'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='fk_task_queue_project'),
        sa.PrimaryKeyConstraint('task_id')
    )
    op.create_index(op.f('ix_task_queue_project_id'), 'task_queue', ['project_id'], unique=False)
    op.create_index(op.f('ix_task_queue_user_id'), 'task_queue', ['user_id'], unique=False)
    op.create_index(op.f('ix_logs_task_id'), 'logs', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_logs_task_id'), table_name='logs')
    op.drop_index(op.f('ix_task_queue_user_id'), table_name='task_queue')
    op.drop_index(op.f('ix_task_queue_project_id'), table_name='task_queue')
    op.drop_table('task_queue')
    # ### end Alembic commands ###
