"""GraphNode comment max len adjust

Revision ID: 0012
Revises: 0011
Create Date: 2025-11-14 16:33:18.807487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '0012'
down_revision: Union[str, Sequence[str], None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('graph_nodes', 'comment',
                    existing_type=sa.VARCHAR(length=4096),
                    type_=sqlmodel.sql.sqltypes.AutoString(length=20480),
                    existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('graph_nodes', 'comment',
                    existing_type=sqlmodel.sql.sqltypes.AutoString(length=20480),
                    type_=sa.VARCHAR(length=4096),
                    existing_nullable=True)
    # ### end Alembic commands ###
