"""UPD task_queue -> tasks

Revision ID: 0014
Revises: 0013
Create Date: 2025-11-28 18:16:23.169095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '0014'
down_revision: Union[str, Sequence[str], None] = '0013'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_queue', sa.Column('message', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('task_queue', sa.Column('started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('task_queue', sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True))
    op.rename_table('task_queue', 'tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('tasks', 'task_queue')
    op.drop_column('task_queue', 'finished_at')
    op.drop_column('task_queue', 'started_at')
    # ### end Alembic commands ###
