"""upd_task_status_enum

Revision ID: 0015
Revises: 0014
Create Date: 2025-12-02 15:24:14.809223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0015'
down_revision: Union[str, Sequence[str], None] = '0014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
                    existing_type=sa.VARCHAR(length=9),
                    type_=sa.Enum('IDLE', 'QUEUED', 'ASSIGNED', 'PENDING', 'STARTED', 'RUNNING', 'SUCCESS', 'ERROR',
                                  'CANCELLED', 'CANCEL_REQUESTED', name='task_queue_status', native_enum=False),
                    existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'status',
                    existing_type=sa.Enum('IDLE', 'QUEUED', 'ASSIGNED', 'PENDING', 'STARTED', 'RUNNING', 'SUCCESS',
                                          'ERROR', 'CANCELLED', 'CANCEL_REQUESTED', name='task_queue_status',
                                          native_enum=False),
                    type_=sa.VARCHAR(length=9),
                    existing_nullable=False)
    # ### end Alembic commands ###
