"""add is_ttl_active, ttl_time, workers_count in project model

Revision ID: 0017
Revises: 0016
Create Date: 2026-01-20 12:58:58.429736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0017'
down_revision: Union[str, Sequence[str], None] = '0016'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('db_connections', 'connection_properties',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('db_connections', 'type',
               existing_type=postgresql.ENUM('mysql', 'postgres', 'clickhouse', 'mongodb', 'mssql', 'kafka', 's3', 'oracle', 'custom', name='connectiontype'),
               nullable=True)
    op.add_column('projects', sa.Column('is_ttl_active', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('ttl_time', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('workers_count', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_task_queue_project_id'), table_name='tasks')
    op.drop_index(op.f('ix_task_queue_user_id'), table_name='tasks')
    op.create_index(op.f('ix_tasks_project_id'), 'tasks', ['project_id'], unique=False)
    op.create_index(op.f('ix_tasks_user_id'), 'tasks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_user_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_project_id'), table_name='tasks')
    op.create_index(op.f('ix_task_queue_user_id'), 'tasks', ['user_id'], unique=False)
    op.create_index(op.f('ix_task_queue_project_id'), 'tasks', ['project_id'], unique=False)
    op.drop_column('projects', 'workers_count')
    op.drop_column('projects', 'ttl_time')
    op.drop_column('projects', 'is_ttl_active')
    op.alter_column('db_connections', 'type',
               existing_type=postgresql.ENUM('mysql', 'postgres', 'clickhouse', 'mongodb', 'mssql', 'kafka', 's3', 'oracle', 'custom', name='connectiontype'),
               nullable=False)
    op.alter_column('db_connections', 'connection_properties',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
