"""UPD project model, UPD graph_node model

Revision ID: 0022
Revises: 0021
Create Date: 2026-01-29 17:49:04.028041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0022'
down_revision: Union[str, Sequence[str], None] = '0021'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'graph_nodes',
        sa.Column(
            'store_enabled',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        )
    )
    op.alter_column(
        'projects',
        'is_ttl_active',
        new_column_name='store_enabled'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'projects',
        'store_enabled',
        new_column_name='is_ttl_active'
    )
    op.drop_column('graph_nodes', 'store_enabled')
    # ### end Alembic commands ###
