"""ADD subgraphs

Revision ID: 0026
Revises: 0025
Create Date: 2026-02-11 13:28:46.937555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '0026'
down_revision: Union[str, Sequence[str], None] = '0025'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subgraphs',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ui_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('position_x', sa.Float(), nullable=False),
    sa.Column('position_y', sa.Float(), nullable=False),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(length=20480), nullable=True),
    sa.Column('project_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['project_id', 'user_id'], ['projects.id', 'projects.user_id'], name='fk_subgraphs_project_user'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ui_id', 'project_id', name='unique_ui_id_per_project_for_subgraphs')
    )
    op.create_index(op.f('ix_subgraphs_ui_id'), 'subgraphs', ['ui_id'], unique=False)
    op.add_column('graph_edges', sa.Column('subgraph_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('graph_nodes', sa.Column('subgraph_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('graph_nodes', 'subgraph_id')
    op.drop_column('graph_edges', 'subgraph_id')
    op.drop_index(op.f('ix_subgraphs_ui_id'), table_name='subgraphs')
    op.drop_table('subgraphs')
    # ### end Alembic commands ###
