"""ADD expanded field to subgraph model

Revision ID: 0030
Revises: 0029
Create Date: 2026-02-24 18:04:49.262208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '0030'
down_revision: Union[str, Sequence[str], None] = '0029'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subgraphs', sa.Column('expanded', sa.Boolean(), nullable=True))
    op.execute(sa.text("UPDATE subgraphs SET expanded = false WHERE expanded IS NULL"))
    op.alter_column('subgraphs', 'expanded', existing_type=sa.Boolean(), nullable=False)
    op.add_column('subgraphs', sa.Column('color', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subgraphs', 'color')
    op.drop_column('subgraphs', 'expanded')
    # ### end Alembic commands ###
