"""add crontab field in Project

Revision ID: 0033
Revises: 0032
Create Date: 2026-03-02 18:25:20.244349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes

# revision identifiers, used by Alembic.
revision: str = '0033'
down_revision: Union[str, Sequence[str], None] = '0032'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('graph_nodes', 'store_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.add_column('projects', sa.Column('crontab', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'crontab')
    op.alter_column('graph_nodes', 'store_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    ### end Alembic commands ###
