"""add_enums_for_tasks

Revision ID: 0044
Revises: 0043
Create Date: 2026-04-01 12:30:44.798999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0044'
down_revision: Union[str, Sequence[str], None] = '0043'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаём ENUM тип перед добавлением колонки
    extensiondepsstatus_enum = sa.Enum('NOT_INSTALLED', 'INSTALLING', 'READY', 'ERROR', name='extensiondepsstatus')
    extensiondepsstatus_enum.create(op.get_bind())

    # Добавляем колонку с server_default для существующих записей
    op.add_column('extensions', sa.Column('deps_status', extensiondepsstatus_enum, nullable=False, server_default='NOT_INSTALLED'))
    op.drop_constraint(op.f('project_schedules_project_id_key'), 'project_schedules', type_='unique')
    op.drop_index(op.f('ix_project_schedules_project_id'), table_name='project_schedules')
    op.create_index(op.f('ix_project_schedules_project_id'), 'project_schedules', ['project_id'], unique=True)
    op.drop_constraint(op.f('project_schedules_scheduled_by_user_id_fkey'), 'project_schedules', type_='foreignkey')
    op.drop_constraint(op.f('project_schedules_project_id_fkey'), 'project_schedules', type_='foreignkey')
    op.create_foreign_key('project_schedules_scheduled_by_user_id_fkey', 'project_schedules', 'users', ['scheduled_by_user_id'], ['id'])
    op.create_foreign_key('project_schedules_project_id_fkey', 'project_schedules', 'projects', ['project_id'], ['id'])
    op.drop_index(op.f('ix_tasks_status_updated_at'), table_name='tasks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_tasks_status_updated_at'), 'tasks', ['status', 'updated_at'], unique=False)
    op.drop_constraint('project_schedules_project_id_fkey', 'project_schedules', type_='foreignkey')
    op.drop_constraint('project_schedules_scheduled_by_user_id_fkey', 'project_schedules', type_='foreignkey')
    op.create_foreign_key(op.f('project_schedules_project_id_fkey'), 'project_schedules', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('project_schedules_scheduled_by_user_id_fkey'), 'project_schedules', 'users', ['scheduled_by_user_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_project_schedules_project_id'), table_name='project_schedules')
    op.create_index(op.f('ix_project_schedules_project_id'), 'project_schedules', ['project_id'], unique=False)
    op.create_unique_constraint(op.f('project_schedules_project_id_key'), 'project_schedules', ['project_id'], postgresql_nulls_not_distinct=False)
    # Удаляем колонку с server_default
    op.drop_column('extensions', 'deps_status')
    # Удаляем ENUM тип
    op.execute('DROP TYPE IF EXISTS extensiondepsstatus')
    # ### end Alembic commands ###
