"""add_extension_license_fields

Revision ID: 0046
Revises: 0045
Create Date: 2026-04-02 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0046'
down_revision: Union[str, Sequence[str], None] = '0045'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Создаём ENUM тип для статуса лицензии
    extensionlicensestatus_enum = sa.Enum(
        'NOT_REQUIRED', 'INACTIVE', 'ACTIVE', 'EXPIRED',
        name='extensionlicensestatus'
    )
    extensionlicensestatus_enum.create(op.get_bind())

    # Добавляем колонки для лицензии расширения
    op.add_column(
        'extensions',
        sa.Column('license_key', sa.String(length=255), nullable=True)
    )
    op.add_column(
        'extensions',
        sa.Column('license_activated_at', sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        'extensions',
        sa.Column('license_expires_at', sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        'extensions',
        sa.Column(
            'license_status',
            extensionlicensestatus_enum,
            nullable=True,
        )
    )

    # Создаём индекс для статуса лицензии
    op.create_index(
        op.f('ix_extensions_license_status'),
        'extensions',
        ['license_status'],
        unique=False
    )

    # Инициализируем существующие расширения — все NOT_REQUIRED по умолчанию
    op.execute("""
        UPDATE extensions 
        SET license_status = 'NOT_REQUIRED'
        WHERE license_status IS NULL
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    
    op.drop_index(op.f('ix_extensions_license_status'), table_name='extensions')
    op.drop_column('extensions', 'license_status')
    op.drop_column('extensions', 'license_expires_at')
    op.drop_column('extensions', 'license_activated_at')
    op.drop_column('extensions', 'license_key')
    
    # Удаляем ENUM тип
    op.execute('DROP TYPE IF EXISTS extensionlicensestatus')
    # ### end Alembic commands ###
