"""Add extensions available versions

Revision ID: 0052
Revises: 0051
Create Date: 2026-05-22 14:15:45.008758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0052'
down_revision: Union[str, Sequence[str], None] = '0051'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('extensions', sa.Column('available_versions', sa.JSON(), nullable=True))
    op.alter_column('extensions', 'license_activated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('extensions', 'license_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index(op.f('ix_extensions_license_status'), table_name='extensions')
    op.drop_constraint(op.f('fk_projects_folder'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'project_folders', ['folder_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_projects_folder'), 'projects', 'project_folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_extensions_license_status'), 'extensions', ['license_status'], unique=False)
    op.alter_column('extensions', 'license_expires_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('extensions', 'license_activated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.drop_column('extensions', 'available_versions')
    # ### end Alembic commands ###
