import os
import sys
import traceback
from pathlib import Path

from sqlalchemy import Engine, inspect
from sqlmodel import Session, select

from alembic import command
from alembic.config import Config
from alembic.migration import MigrationContext

from src.enums import DVTDefaultRoles
from src.logger import logger
from src.utils.user_roles import PRIVILEGED_ROLE_VALUES


def run_alembic_autogenerate_revision(
        alembic_ini: str | Path,
):
    """
    Выполняет команду 'alembic revision --autogenerate -m "message"'.
    """

    if not os.path.exists(alembic_ini):
        logger.error(f"Ошибка: Файл Alembic конфигурации не найден по пути: {alembic_ini}")
        sys.exit(1)

    logger.info(f"Загрузка конфигурации Alembic из: {alembic_ini}")
    alembic_cfg = Config(alembic_ini)

    try:
        logger.info("Запуск автогенерации миграций Alembic...")
        command.revision(alembic_cfg, autogenerate=True, message="UPD autogenerated migration")
        logger.success("Автогенерация миграций Alembic успешно завершена.")
    except Exception as e:
        logger.error(f"Произошла ошибка при выполнении автогенерации миграций Alembic: {e}")
        traceback.print_exc()
        sys.exit(1)


def run_alembic_upgrade_head(
        alembic_ini: str | Path,
        engine: Engine
):
    """
    Выполняет команду 'alembic upgrade head'.
    """

    if not os.path.exists(alembic_ini):
        logger.error(f"Ошибка: Файл Alembic конфигурации не найден по пути: {alembic_ini}")
        sys.exit(1)

    logger.info(f"Загрузка конфигурации Alembic из: {alembic_ini}")
    alembic_cfg = Config(alembic_ini)

    with engine.connect() as connection:
        context = MigrationContext.configure(connection)

        inspector = inspect(connection)
        alembic_version_exists = 'alembic_version' in inspector.get_table_names()

        if not alembic_version_exists or context.get_current_revision() is None:
            logger.warning("Таблица 'alembic_version' не найдена. Выполняем 'stamp' с базовой ревизией 'f86379fd0dd1'.")
            command.stamp(alembic_cfg, "base")
            logger.info("База данных успешно инициализирована Alembic.")

    try:
        logger.info("Запуск миграции Alembic до 'head'...")
        command.upgrade(alembic_cfg, "head")
        logger.success("Миграция Alembic успешно завершена до 'head'.")

    except Exception as e:
        logger.error(f"Произошла ошибка при выполнении миграции Alembic: {e}")
        traceback.print_exc()
        sys.exit(1)
