"""Доменные сервисы: генерация секретов, валидация, работа с .env."""

from __future__ import annotations

import base64
import os
import re
from collections.abc import Mapping

from .models import InstallConfig

FERNET_RE = re.compile(r"^[A-Za-z0-9_-]{43}=$")
AI_MCP_PROFILE = "ai-mcp"
AI_MCP_SECRET_MIN_LENGTH = 32
TRUE_TOKENS = {"1", "true", "yes", "on"}
FALSE_TOKENS = {"0", "false", "no", "off"}
AUTH_SECRET_MIN_LENGTH = 32
AUTH_SECRET_FIELDS = (
    ("jwt_access_token_secret_key", "DVT_JWT_ACCESS_TOKEN_SECRET_KEY"),
    ("jwt_refresh_token_secret_key", "DVT_JWT_REFRESH_TOKEN_SECRET_KEY"),
    ("jwt_onetime_token_secret_key", "DVT_JWT_ONETIME_TOKEN_SECRET_KEY"),
    ("jwt_api_token_secret_key", "DVT_JWT_API_TOKEN_SECRET_KEY"),
    ("code_hash_salt", "DVT_CODE_HASH_SALT"),
)


def generate_password(length_bytes: int = 32) -> str:
    # Аналог: openssl rand -base64 32 | tr '+/' '-_' | tr -d '='
    return (
        base64.b64encode(os.urandom(length_bytes))
        .decode()
        .translate(str.maketrans("+/", "-_"))
        .rstrip("=")
    )


def generate_fernet_key() -> str:
    # Аналог: openssl rand 32 | openssl base64 -A | tr '+/' '-_'
    return base64.urlsafe_b64encode(os.urandom(32)).decode()


def resolve_auth_secrets(existing: Mapping[str, str]) -> dict[str, str]:
    values = {
        env_name: existing.get(env_name, "").strip() or generate_password()
        for _, env_name in AUTH_SECRET_FIELDS
    }
    invalid = [
        name for name, value in values.items() if len(value) < AUTH_SECRET_MIN_LENGTH
    ]
    if invalid:
        raise ValueError(
            "Auth secrets must contain at least "
            f"{AUTH_SECRET_MIN_LENGTH} characters: {', '.join(invalid)}"
        )
    duplicate_names = sorted(
        name
        for name, value in values.items()
        if list(values.values()).count(value) > 1
    )
    if duplicate_names:
        raise ValueError(f"Auth secrets must be unique: {', '.join(duplicate_names)}")
    return values


def populate_install_auth_secrets(
    cfg: InstallConfig,
    existing: Mapping[str, str],
) -> None:
    supplied = dict(existing)
    for field_name, env_name in AUTH_SECRET_FIELDS:
        value = getattr(cfg, field_name).strip()
        if value:
            supplied[env_name] = value

    resolved = resolve_auth_secrets(supplied)
    for field_name, env_name in AUTH_SECRET_FIELDS:
        setattr(cfg, field_name, resolved[env_name])


def is_valid_fernet_key(key: str) -> bool:
    return bool(FERNET_RE.match(key))


def parse_bool_value(value: str | None, *, default: bool = False) -> bool:
    if value is None or not value.strip():
        return default
    normalized = value.strip().lower()
    if normalized in TRUE_TOKENS:
        return True
    if normalized in FALSE_TOKENS:
        return False
    raise ValueError(f"Некорректное булево значение DVT_AI_MCP_ENABLED: {value!r}")


def render_bool(value: bool) -> str:
    return "true" if value else "false"


def update_ai_mcp_profile(value: str | None, *, enabled: bool) -> str:
    profiles = [chunk.strip() for chunk in (value or "").split(",") if chunk.strip()]
    profiles = [profile for profile in profiles if profile != AI_MCP_PROFILE]
    if enabled:
        profiles.append(AI_MCP_PROFILE)
    return ",".join(profiles)


def validate_ai_mcp_secret(secret: str, *, enabled: bool) -> None:
    if not enabled:
        return
    if len(secret) < AI_MCP_SECRET_MIN_LENGTH:
        raise ValueError(
            "DVT_AI_MCP_INTERNAL_SECRET должен содержать не менее "
            f"{AI_MCP_SECRET_MIN_LENGTH} символов"
        )


def render_env_file(cfg: InstallConfig) -> str:
    """Формирует .env в том же формате, что install.sh."""
    return f"""# -----------------------------------------
# DVT .env (generated by update-service)
# -----------------------------------------
COMPOSE_PROJECT_NAME={cfg.project_name}
COMPOSE_PROFILES={update_ai_mcp_profile(None, enabled=cfg.ai_mcp_enabled)}
DVT_VERSION={cfg.version}
DVT_LIB_DIR={cfg.lib_dir_host}
DVT_PUBLIC_URL={cfg.public_url}
DVT_COOKIE_SECURE={cfg.cookie_secure}
DVT_POSTGRES_USER={cfg.postgres_user}
DVT_POSTGRES_PASSWORD={cfg.postgres_password}
DVT_POSTGRES_DB={cfg.postgres_db}
DVT_POSTGRES_HOST=postgres
DVT_POSTGRES_PORT=5432
DVT_VALKEY_HOST=valkey
DVT_VALKEY_PORT=6379
DVT_VALKEY_PASSWORD={cfg.valkey_password}
DVT_VALKEY_DB={cfg.valkey_db}
DVT_CELERY_VISIBILITY_TIMEOUT_SEC=28800
DVT_GRPC_FORWARD_SERVICE_TOKEN={cfg.grpc_token}
DVT_FERNET_KEY={cfg.fernet_key}
DVT_JWT_ACCESS_TOKEN_SECRET_KEY={cfg.jwt_access_token_secret_key}
DVT_JWT_REFRESH_TOKEN_SECRET_KEY={cfg.jwt_refresh_token_secret_key}
DVT_JWT_ONETIME_TOKEN_SECRET_KEY={cfg.jwt_onetime_token_secret_key}
DVT_JWT_API_TOKEN_SECRET_KEY={cfg.jwt_api_token_secret_key}
DVT_CODE_HASH_SALT={cfg.code_hash_salt}
DVT_AI_MCP_ENABLED={render_bool(cfg.ai_mcp_enabled)}
DVT_AI_MCP_INTERNAL_SECRET={cfg.ai_mcp_internal_secret}
DVT_GATEWAY_HOST=gateway
DVT_GATEWAY_PORT=8000
DVT_GATEWAY_INTERNAL_HOST=0.0.0.0
DVT_GATEWAY_INTERNAL_PORT=8000
DVT_TASK_WORKER_HOST=task-worker
DVT_TASK_WORKER_PORT=8000
DVT_TASK_WORKER_INTERNAL_HOST=0.0.0.0
DVT_TASK_WORKER_INTERNAL_PORT=8000
DVT_STORE_HOST=store
DVT_STORE_PORT=50551
DVT_UI_HOST=ui
DVT_UI_PORT=80
DVT_TASK_WORKERS_COUNT={cfg.task_workers_count}
DVT_EXTERNAL_PORT={cfg.external_port}
"""


def parse_env_file(content: str) -> dict[str, str]:
    result: dict[str, str] = {}
    for line in content.splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        key, _, value = line.partition("=")
        result[key.strip()] = value.strip()
    return result


def update_env_values(content: str, values: dict[str, str]) -> str:
    """Обновляет значения ключей в тексте .env, сохраняя остальные строки
    (в т.ч. добавленные вручную). Отсутствующие ключи дописываются в конец."""
    remaining = dict(values)
    lines: list[str] = []
    for line in content.splitlines():
        stripped = line.strip()
        if stripped and not stripped.startswith("#") and "=" in stripped:
            key = stripped.partition("=")[0].strip()
            if key in remaining:
                lines.append(f"{key}={remaining.pop(key)}")
                continue
        lines.append(line)
    for key, value in remaining.items():
        lines.append(f"{key}={value}")
    return "\n".join(lines) + "\n"
